source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'MyPlace' do
  pod 'Alamofire', '~> 4.4'

  # Pods for MyPlace

  target 'MyPlaceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyPlaceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
